import ts from 'typescript';import {createHash} from 'node:crypto';import type {FileNode,SymbolNode,Edge} from '../shared/model.ts';import path from 'node:path';
export const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export function parseFile(p:string,source:string):FileNode{
 const ast=ts.createSourceFile(p,source,ts.ScriptTarget.Latest,true,p.endsWith('.tsx')?ts.ScriptKind.TSX:ts.ScriptKind.TS);const symbols:SymbolNode[]=[];const imports:FileNode['imports']=[];
 function visit(n:ts.Node,parent=''){
 if(ts.isImportDeclaration(n)&&ts.isStringLiteral(n.moduleSpecifier)){const bindings=n.importClause?.namedBindings;const names=bindings&&ts.isNamedImports(bindings)?bindings.elements.map(x=>x.name.text):bindings&&ts.isNamespaceImport(bindings)?[bindings.name.text]:[];if(n.importClause?.name)names.push(n.importClause.name.text);for(const name of names.length?names:['*'])imports.push({name,specifier:n.moduleSpecifier.text});}
 let kind='';let name='';
 if(ts.isFunctionDeclaration(n)){kind='function';name=n.name?.text||'default';}else if(ts.isClassDeclaration(n)){kind='class';name=n.name?.text||'default';}else if(ts.isInterfaceDeclaration(n)){kind='interface';name=n.name.text;}else if(ts.isTypeAliasDeclaration(n)){kind='type';name=n.name.text;}else if(ts.isMethodDeclaration(n)){kind='method';name=n.name.getText(ast);}else if(ts.isVariableDeclaration(n)&&n.initializer&&(ts.isArrowFunction(n.initializer)||ts.isFunctionExpression(n.initializer))){kind='function';name=n.name.getText(ast);}
 let qualified=parent;if(kind){qualified=parent?`${parent}.${name}`:name;const text=n.getText(ast);const normalized=text.replace(/\b[A-Za-z_$][\w$]*\b/g,'I').replace(/\s+/g,'');const exported=ts.canHaveModifiers(n)&&!!ts.getModifiers(n)?.some(m=>m.kind===ts.SyntaxKind.ExportKeyword)||ts.isVariableDeclaration(n)&&n.parent.parent.getText(ast).startsWith('export');if(['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].includes(name)&&exported)kind='route';
 symbols.push({id:hash(`${p}:${qualified}:${n.pos}`).slice(0,20),name,qualified,path:p,kind,line:ast.getLineAndCharacterOfPosition(n.getStart(ast)).line+1,end:ast.getLineAndCharacterOfPosition(n.end).line+1,signature:text.slice(0,text.indexOf('{')<0?160:text.indexOf('{')).slice(0,220),fingerprint:hash(normalized),complexity:1+(text.match(/\b(if|for|while|case|catch)\b|\?\?|&&|\|\|/g)||[]).length,exported:!!exported,confidence:1,evidence:'AST declaration'});}
 ts.forEachChild(n,c=>visit(c,qualified));}visit(ast);return {path:p,hash:hash(source),imports,symbols};
}
export function dependencies(files:FileNode[],sources:Map<string,string>):Edge[]{const edges:Edge[]=[];const byPath=new Map(files.map(f=>[f.path,f]));
 for(const file of files){for(const symbol of file.symbols)edges.push({source:`file:${file.path}`,target:symbol.id,kind:'defines',confidence:1,evidence:`${file.path}:${symbol.line}`});
 for(const imp of file.imports){if(!imp.specifier.startsWith('.'))continue;const base=path.posix.normalize(path.posix.join(path.posix.dirname(file.path),imp.specifier)).replace(/\.js$/,'');const target=[base,base+'.ts',base+'.tsx',base+'/index.ts',base+'/index.tsx'].map(p=>byPath.get(p)).find(Boolean);if(!target)continue;
 edges.push({source:`file:${file.path}`,target:`file:${target.path}`,kind:/\.(test|spec)\.tsx?$/.test(file.path)?'tests':'imports',confidence:1,evidence:`import ${imp.name} from ${imp.specifier}`});
 const dest=target.symbols.find(s=>s.name===imp.name&&s.exported);if(dest){for(const sym of file.symbols){const body=(sources.get(file.path)||'').split('\n').slice(sym.line-1,sym.end).join('\n');if(new RegExp(`\\b${imp.name.replace(/[$]/g,'\\$')}\\s*\\(`).test(body))edges.push({source:sym.id,target:dest.id,kind:'calls',confidence:0.75,evidence:`Imported identifier call in ${file.path}:${sym.line}; shadowing not resolved`});}}
 }}return edges.filter((e,i,a)=>a.findIndex(x=>x.source===e.source&&x.target===e.target&&x.kind===e.kind)===i);}
